#!/usr/bin/env bash
#script that displays To infinity and beyond indefinitely
#Requirement: between each iteration of the loop, add a sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done

